config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => { registrations: 'users/registrations' }
  devise_for :makers, :controllers => { registrations: 'makers/registrations' }

  authenticated :user do
    root to: 'general#home', as: :user_root
  end

  authenticated :maker do
    root to: 'makers#show', as: :maker_root
  end
  
  unauthenticated do
    root to: 'prospects#new', as: :unauthenticated_root
  end

  resources :users
  resources :makers do
    member do
      get :payment
    end
  end
  resources :products do
    resources :build, controller: 'products/build'
    resources :uploads, only: [:new, :create, :destroy]
  end
  resources :reviews do
    resources :build, controller: 'reviews/build'
  end
  resources :charges
  resources :prospects, only: [:new, :create, :show]

  get '/search', to: 'search#search'
  get '/about', to: 'general#about'
  get '/', to: 'general#home'
  get '/dash/:id', to: 'products#dash', as: 'dash'
  get '/thanks', to: 'prospects#thanks'
  get '/stripe_connect', to: 'makers#stripe_connect'
end

app/models/product.rb
require 'elasticsearch/model'

class Product < ActiveRecord::Base
	include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  scope :active, -> { where(status: 'active') }
  scope :pending, -> { where(status: 'pending') }
  scope :started, -> { where(status: nil) }
  scope :past, -> { where(status: 'past') }

	belongs_to :maker
	has_many :reviews
	has_many :users, through: :reviews
	has_many :uploads, dependent: :destroy

	validates :name, presence: true, length: { maximum: 50 }, :if => :pending?
	validates :description, presence: true, length: { maximum: 50 }, :if => :pending?
	validates :price, presence: true, :if => :pending?
	validates :rebate, presence: true, :if => :pending?
	validate :rebate_is_less_than_or_equal_to_price
	validates :quantity, presence: true, :if => :pending?
	validates :story, presence: true, length: { maximum: 10000 }, :if => :pending?

  settings index: { number_of_shards: 1 }

 #  def as_indexed_json(options = {})
	#   self.as_json({
	#     only: [:name],
	#     include: {
	#       maker: { only: :company }
	#     }
	#   })
	# end

	private

		def pending?
	    status == 'pending'
	  end

	  def rebate_is_less_than_or_equal_to_price
	  	if pending? and price != nil and rebate != nil and rebate > price
	  		errors.add(:rebate, "should not be greater than price")
	  	end
	  end
end

Product.import

app/controllers/products/build_controller.rb
class Products::BuildController < ApplicationController
  include Wicked::Wizard

  before_action :authenticate_maker!
  before_action :correct_maker

  steps :product, :questions, :payment, :preview

  def show
    @product = Product.find(params[:product_id])
    render_wizard
  end

  def update
    @product = Product.find(params[:product_id])
    if step == steps.last
      @product.status = "pending"
      if @product.save
        redirect_to @product.maker
      else
        @product.status = ""
        render :preview
      end
    else
      if @product.update_attributes(build_params)
        render_wizard @product
      else
        flash[:error] = "There was an error, please try again."
        redirect_to :back
      end
    end
  end

  private

    def build_params
      params.require(:product).permit(:name, :description, :youtube_url, :price, :rebate, :quantity,
                                      :image1, :image2, :image3, :image4, :image5, :story,
                                      :q1, :q2, :q3, :q4, :q5, :q6, :q7, :q8, :q9, :q10,
                                      :q11, :q12, :q13, :q14, :q15, :q16, :q17, :q18, :q19, :q20)
    end

    def correct_maker
      @maker = Product.find(params[:product_id]).maker
      if @maker != current_maker
        flash[:error] = "No access permission."
        redirect_to(root_url)
      end
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

	before_action :authenticate_maker!, except: [:show]
	before_action :correct_maker, only: [:edit, :update, :destroy]

	def new
		@product = Product.new
	end

	def create
		@product = current_maker.products.build(product_params)
		if @product.save
			redirect_to product_build_path(:product, product_id: @product.id)
		else
			flash.now[:error] = "There was an error, please try again."
			render 'new'
		end
	end

	def edit
		@product = Product.find(params[:id])
	end

	def update
		@product = Product.find(params[:id])
		if @product.update_attributes(product_params)
      flash[:success] = "Product updated!"
      redirect_to @product
    else
    	flash.now[:error] = "There was an error, please try again."
      render 'edit'
    end
  end

  def destroy
  	@product = current_maker.products.find_by(id: params[:id])
  	redirect_to root_path if @product.nil?
  	@product.destroy
  	redirect_to current_maker
  end

	def show
		@product = Product.find(params[:id])
	end

	def dash
		@product = Product.find(params[:id])
		@reviews = @product.reviews
	end

	private

		def product_params
			params.require(:product).permit(:status, :name, :description, :youtube_url, :price, :rebate, :quantity,
																			:image1, :image2, :image3, :image4, :image5, :story,
																			:q1, :q2, :q3, :q4, :q5, :q6, :q7, :q8, :q9, :q10,
																			:q11, :q12, :q13, :q14, :q15, :q16, :q17, :q18, :q19, :q20)
		end

		def correct_maker
			@maker = Product.find(params[:id]).maker
			if @maker != current_maker
				flash[:error] = "No access permission."
				redirect_to(root_url)
			end
		end
end

app/helpers/products_helper.rb
module ProductsHelper

	def youtube_id(youtube_url)
  	return youtube_url.split("=").last
  end

  def embed(youtube_url)
    youtube_id = youtube_id(youtube_url)
    content_tag(
    						:iframe, 
    						nil, 
    						src: "//www.youtube.com/embed/#{youtube_id}?modestbranding=1&autohide=1&showinfo=0")
  end
end

app/views/products/_dash_product.html.erb
<li class="dash-product">
	<% if product.status == "active" %>
		<%= link_to product_path(product) do %>
			<% if product.uploads.length == 0 %>
				<%= image_tag("image_not_found_small.png") %>
			<% else %>
				<%= image_tag product.uploads[0].image.url(:thumb) %>
			<% end %>
			<div class="dash-button-left"><%= product.name %></div>
		<% end %>
		<div class="dash-button-right">
			<a onclick="dashDropdown(<%= product.id %>)" id="dash-dropdown-btn-<%= product.id%>" class="dash-dropdown-btn"><i class="fa fa-ellipsis-h fa-lg" aria-hidden="true"></i></a>
			<div id="dash-dropdown-<%= product.id %>" class="dash-dropdown">
		    <%= link_to "View", product_path(product) %>
		    <%= link_to "Reviews", dash_path(product) %>
		  </div>
		</div>
	<% elsif product.status == "pending" %>
		<%= link_to product_build_path(:product, product_id: product.id) do %>
			<% if product.uploads.length == 0 %>
				<%= image_tag("image_not_found_small.png") %>
			<% else %>
				<%= image_tag product.uploads[0].image.url(:thumb) %>
			<% end %>
			<div class="dash-button-left"><%= product.name %></div>
		<% end %>
		<div class="dash-button-right">
			<a onclick="dashDropdown(<%= product.id %>)" id="dash-dropdown-btn-<%= product.id%>" class="dash-dropdown-btn"><i class="fa fa-ellipsis-h fa-lg" aria-hidden="true"></i></a>
			<div id="dash-dropdown-<%= product.id %>" class="dash-dropdown">
		    <%= link_to "Edit", product_build_path(:product, product_id: product.id) %>
		    <%= link_to "Delete", product, method: :delete,
                                  data: { confirm: "You sure?" } %>
		  </div>
		</div>
	<% elsif !product.status %>
		<%= link_to product_build_path(:product, product_id: product.id) do %>
			<% if product.uploads.length == 0 %>
				<%= image_tag("image_not_found_small.png") %>
			<% else %>
				<%= image_tag product.uploads[0].image.url(:thumb) %>
			<% end %>
			<div class="dash-button-left"><%= product.name %></div>
		<% end %>
		<div class="dash-button-right">
			<a onclick="dashDropdown(<%= product.id %>)" id="dash-dropdown-btn-<%= product.id%>" class="dash-dropdown-btn"><i class="fa fa-ellipsis-h fa-lg" aria-hidden="true"></i></a>
			<div id="dash-dropdown-<%= product.id %>" class="dash-dropdown">
		    <%= link_to "Edit", product_build_path(:product, product_id: product.id) %>
		    <%= link_to "Delete", product, method: :delete,
                                  data: { confirm: "You sure?" } %>
		  </div>
		</div>
	<% elsif product.status == "complete" %>
		<%= link_to dash_path(product) do %>
			<% if product.uploads.length == 0 %>
				<%= image_tag("image_not_found_small.png") %>
			<% else %>
				<%= image_tag product.uploads[0].image.url(:thumb) %>
			<% end %>
			<div class="dash-button-left"><%= product.name %></div>
		<% end %>
		<div class="dash-button-right">
			<a onclick="dashDropdown(<%= product.id %>)" id="dash-dropdown-btn-<%= product.id%>" class="dash-dropdown-btn"><i class="fa fa-ellipsis-h fa-lg" aria-hidden="true"></i></a>
			<div id="dash-dropdown-<%= product.id %>" class="dash-dropdown">
		    <%= link_to "View", product_path(product) %>
		    <%= link_to "Reviews", dash_path(product) %>
		  </div>
		</div>
	<% end %>
</li>

app/views/products/_product.html.erb
<li class="product-card">
	<%= link_to product do %>
		<% if product.uploads.length == 0 %>
			<%= image_tag("image_not_found.png") %>
		<% else %>
			<%= image_tag product.uploads[0].image.url(:medium) %>
		<% end %>
		<div class="product-card-info">
			<div class="product-card-name"><%= product.name %></div>
			<div class="product-card-company"><%= product.maker.company %></div>
			<div class="product-card-desc"><%= product.description %></div>
			<div class="product-card-price">$<%= product.price %></div>
		</div>
	<% end %>
</li>

app/views/products/dash.html.erb
<div class="container">
	<% if @reviews.length == 0 %>
		<br />
		<div class="small-title">No reviews yet</div>
	<% else %>
		<div class="subtitle">Reviews</div>
		<table class="reviews-table">
			<tr>
		    <td></td>
		    <td>Reviewer</td> 
		    <td>Some number</td>
		  </tr>
			<% for i in 0..@reviews.length-1 %>
			  <tr>
			    <td><%= i+1 %></td>
			    <td><%= link_to @reviews.first.user.name, @reviews.first %></td> 
			    <td>50</td>
			  </tr>
		  <% end %>
		</table>
	<% end %>
</div>

app/views/products/edit.html.erb
<div class="form-wrapper product-form">
	
	<h2>Edit your product</h2>

	<hr>

	<%= simple_form_for @product do |f| %>

		<div class="form-inputs">
			<%= f.input :image1, as: :file, label: "Main image" %>
			<%= f.input :image2, as: :file, label: "Image 2" %>
			<%= f.input :image3, as: :file, label: "Image 3" %>
			<%= f.input :image4, as: :file, label: "Image 4" %>
			<%= f.input :image5, as: :file, label: "Image 5" %>
			<%= f.input :name, label: "Product name" %>
			<%= f.input :description, label: "One-line description" %>
			<%= f.input :price, label: "Full price" %>
			<%= f.input :rebate %>
			<%= f.input :quantity %>
			<%= f.input :story %>
			<%= f.input :q1 %>
			<%= f.input :q2 %>
			<%= f.input :q3 %>
			<%= f.input :q4 %>
			<%= f.input :q5 %>
			<%= f.input :q6 %>
			<%= f.input :q7 %>
			<%= f.input :q8 %>
			<%= f.input :q9 %>
			<%= f.input :q10 %>
			<%= f.input :q11 %>
			<%= f.input :q12 %>
			<%= f.input :q13 %>
			<%= f.input :q14 %>
			<%= f.input :q15 %>
			<%= f.input :q16 %>
			<%= f.input :q17 %>
			<%= f.input :q18 %>
			<%= f.input :q19 %>
			<%= f.input :q20 %>
		</div>

		<div class="form-actions">
	    <%= f.button :submit, "Submit" %>
	  </div>
	<% end %>

	<%= link_to "Delete", @product, method: :delete,
	                                data: { confirm: "You sure?" } %>
</div>

app/views/products/new.html.erb
<div class="container">

	<div class="subtitle">
		We will help you launch, market and improve your products
	</div>

	<div class="form-wrapper product-form">

		<%= simple_form_for @product, html: { autocomplete: "off" } do |f| %>

			<div class="form-inputs start-caption">
				<span>What are you making?</span>
				<%= f.input :name, required: true, placeholder: "Name" %>
			</div>

			<div class="form-actions">
		    <%= f.button :submit, "Start now" %>
		  </div>
		<% end %>
	</div>

	<ul class="product-instructions">
		<li>
			<i class="fa fa-pencil-square-o fa-2x" aria-hidden="true"></i>
			<br />
			Tell us basic info about your product and upload relevant images/videos
		</li>
		<li>
			<i class="fa fa-question-circle fa-2x" aria-hidden="true"></i>
			<br />
			Compose review questions you'd like your users to answer
		</li>
		<li>
			<i class="fa fa-rocket fa-2x" aria-hidden="true"></i>
			<br />
			Submit your product for approval and launch to our community
		</li>
		<li>
			<i class="fa fa-comments-o fa-2x" aria-hidden="true"></i>
			<br />
			Gain valuable feedback from your users and iterate on your product
		</li>
	</ul>
</div>

app/views/products/show.html.erb
<div class="container">
	<div class="product">
		<div class="row">

			<div class="col-7">
				<div id="product-carousel" class="carousel slide carousel-fade" data-ride="carousel" data-interval="false">

				  <!-- Indicators -->
				  <!-- <ol class="carousel-indicators">
				  	<% if @product.uploads.length > 0 %>
					    <li data-target="#product-carousel" data-slide-to="0" class="active"></li>
					  <% end %>
					  <% for i in 1..@product.uploads.length - 1 %>
					    <li data-target="#product-carousel" data-slide-to=<%= i %>></li>
					  <% end %>
				  </ol> -->

				  <!-- Wrapper for slides -->
				  <div class="carousel-inner" role="listbox">
				  	<% if @product.uploads.length > 0 %>
					    <div class="item active">
					      <%= image_tag @product.uploads[0].image.url(:large) %>
					    </div>
					  <% end %>
				  	<% for i in 1..@product.uploads.length - 1 %>
					    <div class="item">
					      <%= image_tag @product.uploads[i].image.url(:large) %>
					    </div>
					  <% end %>
					  <% if @product.youtube_url.present? %>
						  <div class="item video">
						  	<div class="embed-container">
									<%= embed(@product.youtube_url) %>
								</div>
						  </div>
						<% end %>
				  </div>
				</div>
			</div>

			<div class="col-2">
				<ul class="thumbnails">
					<li><%= image_tag @product.uploads[0].image.url(:thumb), class: "selected", 'data-target' => "#product-carousel", 'data-slide-to' => 0 %></li>
					<% for i in 1..@product.uploads.length - 1 %>
						<li><%= image_tag @product.uploads[i].image.url(:thumb), 'data-target' => "#product-carousel", 'data-slide-to' => i %></li>
					<% end %>
					<% if @product.youtube_url.present? %>
						<li id="separator"></li>
						<li>
							<%= image_tag "//img.youtube.com/vi/" + youtube_id(@product.youtube_url) + "/mqdefault.jpg", 'data-target' => "#product-carousel", 'data-slide-to' => @product.uploads.length %>
							<i class="fa fa-play-circle-o" aria-hidden="true" data-target="#product-carousel", data-slide-to=<%= @product.uploads.length %>></i>
						</li>
						<li id="play-video">Play video</li>
					<% end %>
				</ul>
			</div>

			<div class="col-3 overview">
				<div class="product-show-name"><%= @product.name if @product.name.present? %></div>
				<div class="product-show-maker"><%= @product.maker.company if @product.maker.company.present? %></div>
				<div class="product-show-desc"><%= @product.description if @product.description.present? %></div>
				<div class="product-show-price"><%= '$' + (@product.price - @product.rebate).to_s if @product.price.present? && @product.rebate.present? %></div>
				<div class="product-show-price-reg"><%= 'Regular price: $' + @product.price.to_s if @product.price.present? %></div>

				<ul>
					<li>Free shipping</li>
					<li>Available in the U.S.</li>
				</ul>

				<% if user_signed_in? %>
					<%= link_to "Buy now", "#payment", "data-toggle" => "modal", class: "payment-btn" %>
					<%= render "charges/payment_modal" %>
				<% end %>

				<% if user_signed_in? %>
					<% @review = Review.find_by(user_id: current_user.id, product_id: @product.id) %>
					<% if @review != nil %>
						<%= link_to "Continue review", review_build_path(:context, review_id: @review.id) %>
					<% end %>
				<% end %>
			</div>
		</div>
		<div class="product-section">
			<div class="small-subtitle">Product Story</div>
			<h5>
				<%= sanitize @product.story %>
			</h5>
		</div>
	</div>
</div>