config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => { registrations: 'users/registrations' }
  devise_for :makers, :controllers => { registrations: 'makers/registrations' }

  authenticated :user do
    root to: 'general#home', as: :user_root
  end

  authenticated :maker do
    root to: 'makers#show', as: :maker_root
  end
  
  unauthenticated do
    root to: 'prospects#new', as: :unauthenticated_root
  end

  resources :users
  resources :makers do
    member do
      get :payment
    end
  end
  resources :products do
    resources :build, controller: 'products/build'
    resources :uploads, only: [:new, :create, :destroy]
  end
  resources :reviews do
    resources :build, controller: 'reviews/build'
  end
  resources :charges
  resources :prospects, only: [:new, :create, :show]

  get '/search', to: 'search#search'
  get '/about', to: 'general#about'
  get '/', to: 'general#home'
  get '/dash/:id', to: 'products#dash', as: 'dash'
  get '/thanks', to: 'prospects#thanks'
  get '/stripe_connect', to: 'makers#stripe_connect'
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/ip_address.rb
class IpAddress < ActiveRecord::Base
end

app/models/maker.rb
class Maker < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  has_many :products, dependent: :destroy

  validates :name, presence: true, length: { maximum: 50 }
  validates :email,
    presence: true,
    length: { maximum: 255 }, 
    format: { with: VALID_EMAIL_REGEX }, 
    uniqueness: { case_sensitive: false }
  validates :company, presence: true, length: { maximum: 50 }
  validates :website, presence: true, :url => true
end

app/models/product.rb
require 'elasticsearch/model'

class Product < ActiveRecord::Base
	include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  scope :active, -> { where(status: 'active') }
  scope :pending, -> { where(status: 'pending') }
  scope :started, -> { where(status: nil) }
  scope :past, -> { where(status: 'past') }

	belongs_to :maker
	has_many :reviews
	has_many :users, through: :reviews
	has_many :uploads, dependent: :destroy

	validates :name, presence: true, length: { maximum: 50 }, :if => :pending?
	validates :description, presence: true, length: { maximum: 50 }, :if => :pending?
	validates :price, presence: true, :if => :pending?
	validates :rebate, presence: true, :if => :pending?
	validate :rebate_is_less_than_or_equal_to_price
	validates :quantity, presence: true, :if => :pending?
	validates :story, presence: true, length: { maximum: 10000 }, :if => :pending?

  settings index: { number_of_shards: 1 }

 #  def as_indexed_json(options = {})
	#   self.as_json({
	#     only: [:name],
	#     include: {
	#       maker: { only: :company }
	#     }
	#   })
	# end

	private

		def pending?
	    status == 'pending'
	  end

	  def rebate_is_less_than_or_equal_to_price
	  	if pending? and price != nil and rebate != nil and rebate > price
	  		errors.add(:rebate, "should not be greater than price")
	  	end
	  end
end

Product.import

app/models/prospect.rb
class Prospect < ActiveRecord::Base
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

	before_create :create_referral_code

  belongs_to :referrer, class_name: 'Prospect', foreign_key: 'referrer_id'
  has_many :referrals, class_name: 'Prospect', foreign_key: 'referrer_id'

	validates :email,
    presence: true,
    length: { maximum: 255 }, 
    format: { with: VALID_EMAIL_REGEX }, 
    uniqueness: { case_sensitive: false, message: "This email already exists" }
  validates :referral_code, uniqueness: true, allow_blank: true

  private

  	def create_referral_code
	    self.referral_code = ProspectsHelper.unused_referral_code
	  end
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :user
	belongs_to :product

	validates :user_id, presence: true
	validates :product_id, presence: true, uniqueness: { scope: :user_id }

	def active?
    status == 'active'
  end
end

app/models/upload.rb
class Upload < ActiveRecord::Base

	belongs_to :product

	has_attached_file :image, 
		:styles => { 
			large: "640x480#", 
			medium: "320x240#", 
			thumb: "60x45#" 
		},
		:s3_protocol => :https

	
	validates_attachment :image,
				presence: true,
				content_type: { content_type: /\Aimage\/.*\Z/ },
				size: { :less_than => 1.megabyte }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  VALID_ZIP_REGEX = /\A\d{5}(-\d{4})?\z/

  has_many :reviews
  has_many :products, through: :reviews

  has_attached_file :avatar, 
    styles: { 
      medium: "150x150>", 
      thumb: "50x50>" 
    }, 
    default_url: "/images/:style/missing.png",
    :s3_protocol => :https
  
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  validates :name, length: { maximum: 50 }
  validates :address, length: { maximum: 100 }
  validates :city, length: { maximum: 50 }
  validates :zip, format: { with: VALID_ZIP_REGEX }, allow_blank: true
  validates :email,
    presence: true,
    length: { maximum: 255 }, 
    format: { with: VALID_EMAIL_REGEX }, 
    uniqueness: { case_sensitive: false }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def show
		@user = User.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper

	# Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Polymyr"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-danger"> <button type="button"
    class="close" data-dismiss="alert">×</button>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/general_helper.rb
module GeneralHelper
end

app/helpers/makers_helper.rb
module MakersHelper
end

app/helpers/products_helper.rb
module ProductsHelper

	def youtube_id(youtube_url)
  	return youtube_url.split("=").last
  end

  def embed(youtube_url)
    youtube_id = youtube_id(youtube_url)
    content_tag(
    						:iframe, 
    						nil, 
    						src: "//www.youtube.com/embed/#{youtube_id}?modestbranding=1&autohide=1&showinfo=0")
  end
end

app/helpers/prospects_helper.rb
module ProspectsHelper

	def self.unused_referral_code
    referral_code = SecureRandom.hex(5)
    collision = Prospect.find_by_referral_code(referral_code)

    until collision.nil?
      referral_code = SecureRandom.hex(5)
      collision = Prospect.find_by_referral_code(referral_code)
    end
    referral_code
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_bare_header.html.erb
<nav class="bare-nav">
	<div class="logo"><a href=<%= root_path %>>POLYMYR</a></div>
</nav>

app/views/layouts/_footer.html.erb
<div class="footer">

	<ul class="footer-links">
		<li><%= link_to "About", about_path %></li>
		<li><%= link_to "Blog", "http://www.polymyr.squarespace.com/blog" %></li>
	</ul>

	<div class="footer-contact">
		Get in touch with us at <a href="mailto:contact@polymyr.com">contact@polymyr.com</a>
	</div>

	<div class="footer-bottom">
		<i>Copyright &#169 2016 Polymyr</i>
	</div>
</div>

app/views/layouts/_header.html.erb
<% if user_signed_in? %>
  <nav class="nav nav-fixed">
		<div class="logo"><a href=<%= user_root_path %>>POLYMYR</a></div>
		<ul class="menu">
			<li>
				<%= form_for :search, url: search_path, method: :get, html: { class: "search-form" } do |f| %>
				    <%= text_field_tag :query, params[:query], id: "search-bar" %>
				    <button type="submit" id="search-btn">
						  <i class="fa fa-search" aria-hidden="true"></i>
						</button>
				<% end %>
				<div style="clear: both;"></div>
			</li>
			<li><%= link_to "Profile", current_user %></li>
			<li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
		</ul>
	</nav>
<% elsif maker_signed_in? %>
  <nav class="nav nav-top">
		<div class="logo"><a href=<%= maker_root_path %>>POLYMYR</a></div>
		<ul class="menu">
			<li><%= link_to "Launch", new_product_path %></li>
			<li><%= link_to "Dashboard", current_maker %></li>
			<li>
				<a onclick="headerDropdown()" id="header-dropdown-btn">Account <i class="fa fa-angle-down fa-lg" aria-hidden="true"></i></a>
				<div id="header-dropdown">
					<!-- <i class="fa fa-caret-up fa-lg" aria-hidden="true"></i> -->
			    <%= link_to "Settings", edit_maker_registration_path %>
			    <%= link_to "Payment", payment_maker_path(current_maker) %>
			    <%= link_to "Log out", destroy_maker_session_path, method: :delete %>
			  </div>
			</li>
		</ul>
	</nav>
<% elsif devise_controller? && resource_name == :maker %>
  <nav class="nav nav-top">
		<div class="logo"><a href=<%= maker_root_path %>>POLYMYR</a></div>
	</nav>
<% else %>
  <nav class="nav nav-top">
		<div class="logo"><a href=<%= unauthenticated_root_path %>>POLYMYR</a></div>
		<ul class="menu">
			<li><%= link_to "Sign up", "#signup", "data-toggle" => "modal", "data-dismiss" => "modal" %></li>
			<li><%= link_to "Sign in", "#signin", "data-toggle" => "modal", "data-dismiss" => "modal" %></li>
		</ul>
	</nav>
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
  	<!--<a href="#" data-dismiss="alert" class="close">×</a>-->
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

app/views/layouts/_prelaunch_header.html.erb
<% if action_name == "new" || action_name == "create" %>	
	<nav class="prelaunch-nav white">
		<div class="logo"><a href=<%= unauthenticated_root_path %>>POLYMYR</a></div>
		<ul class="prelaunch-menu">
			<li><%= link_to "List your product", new_maker_session_path %></li>
		</ul>
	</nav>
<% else %>
	<nav class="prelaunch-nav">
		<div class="logo"><a href=<%= unauthenticated_root_path %>>POLYMYR</a></div>
		<ul class="prelaunch-menu">
			<li><%= link_to "List your product", new_maker_session_path %></li>
		</ul>
	</nav>
<% end %>

app/views/layouts/_product_error_messages.html.erb
<% if @product.errors.any? %>
  <div id="error_explanation">
    <ul>
    <% @product.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600' rel='stylesheet' type='text/css'>
    <script type="text/javascript" src="https://js.stripe.com/v2/"></script>
    <script type="text/javascript">
      Stripe.setPublishableKey("<%= Rails.configuration.stripe[:publishable_key] %>");
    </script>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-55613013-4', 'auto');
      ga('send', 'pageview');

    </script>
    <%= render 'favicon' %>
  </head>
  <body>
    <%= render 'layouts/messages' %>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
  <%= render "shared/signin_modal" %>
  <%= render "shared/signup_modal" %>
</html>

app/views/layouts/prelaunch_application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="description" content="The first ever feedback-driven marketplace for incredible hardware products.">
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600' rel='stylesheet' type='text/css'>
    <script type="text/javascript" src="https://js.stripe.com/v2/"></script>
    <script type="text/javascript">
      Stripe.setPublishableKey("<%= Rails.configuration.stripe[:publishable_key] %>");
    </script>
    <%= render 'favicon' %>
  </head>
  <body>
    <%= render 'layouts/messages' %>
    <%= render 'layouts/prelaunch_header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/shared/_signin_modal.html.erb
<div class="modal fade" id="signin" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <div class="form-wrapper">

        <div class="small-title">Sign in</div>

        <% resource = :user %>
        <% resource_name = :user %>
        <% devise_mapping = Devise.mappings[:user] %>

        <%= simple_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
          <%= f.error_notification %>

          <div class="form-inputs">
            <%= f.input :email, placeholder: "Email", autofocus: true %>
            <%= f.input :password, placeholder: "Password" %>
            <%= f.input :remember_me, as: :boolean if devise_mapping.rememberable? %>
          </div>

          <div class="form-actions">
            <%= f.button :submit, "Sign in" %>
          </div>
        <% end %>

				<%- if devise_mapping.registerable? %>
				  <%= link_to "Sign up", "#signup", "data-toggle" => "modal", "data-dismiss" => "modal" %><br />
				<% end -%>

				<%- if devise_mapping.recoverable? %>
				  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
				<% end -%>

				<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
				  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
				<% end -%>

				<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
				  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
				<% end -%>

				<%- if devise_mapping.omniauthable? %>
				  <%- resource_class.omniauth_providers.each do |provider| %>
				    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
				  <% end -%>
				<% end -%>
      </div>
    </div>
  </div>
</div>

app/views/shared/_signup_modal.html.erb
<div class="modal fade" id="signup" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <div class="form-wrapper">

        <div class="small-title">Sign up</div>

        <% resource = :user %>
        <% resource_name = :user %>
        <% devise_mapping = Devise.mappings[:user] %>

        <%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
          <%= f.error_notification %>

          <div class="form-inputs">
            <%= f.input :email, placeholder: "Email", autofocus: true %>
            <%= f.input :password, placeholder: "Password", hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length) %>
          </div>

          <div class="form-actions">
            <%= f.button :submit, "Sign up" %>
          </div>
        <% end %>

        <%= link_to "Sign in", "#signin", "data-toggle" => "modal", "data-dismiss" => "modal" %><br />

      <!--
        <%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
          <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
        <% end -%>
      -->

        <%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
          <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
        <% end -%>

        <%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
          <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
        <% end -%>

        <%- if devise_mapping.omniauthable? %>
          <%- resource_class.omniauth_providers.each do |provider| %>
            <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
          <% end -%>
        <% end -%>
      </div>
    </div>
  </div>
</div>

app/views/welcome/_signin_modal.html.erb
<div class="modal fade" id="signin" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Sign in to Polymyr</h4>
      </div>
      <div class="form-wrapper">

        <%= simple_form_for(:user, :url => session_path(:user)) do |f| %>
          <div class="form-inputs">
            <%= f.input :email, required: false, autofocus: true %>
            <%= f.input :password, required: false %>
            <%= f.input :remember_me, as: :boolean if devise_mapping.rememberable? %>
          </div>

          <div class="form-actions">
            <%= f.button :submit, "Sign in" %>
          </div>
        <% end %>
      </div>

      <div class="modal-footer">
				<%- if devise_mapping.registerable? %>
				  <%= link_to "Sign up", "#signup", "data-toggle" => "modal", "data-dismiss" => "modal" %><br />
				<% end -%>

				<%- if devise_mapping.recoverable? %>
				  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
				<% end -%>

				<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
				  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
				<% end -%>

				<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
				  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
				<% end -%>

				<%- if devise_mapping.omniauthable? %>
				  <%- resource_class.omniauth_providers.each do |provider| %>
				    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
				  <% end -%>
				<% end -%>
      </div>
    </div>
  </div>
</div>

app/views/welcome/_signup_modal.html.erb
<div class="modal fade" id="signup" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Sign up for Polymyr</h4>
      </div>
      <div class="form-wrapper">

        <%= simple_form_for(:user, :url => registration_path(:user)) do |f| %>

          <div class="form-inputs">
            <%= f.input :name, required: true, label: 'Full name', autofocus: true %>
            <%= f.input :email, required: true, autofocus: true %>
            <%= f.input :password, required: true, hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length) %>
          </div>

          <div class="form-actions">
            <%= f.button :submit, "Sign up" %>
          </div>
        <% end %>
      </div>
      <div class="modal-footer">
        <%= link_to "Sign in", "#signin", "data-toggle" => "modal", "data-dismiss" => "modal" %><br />

      <!--
        <%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
          <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
        <% end -%>
      -->

        <%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
          <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
        <% end -%>

        <%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
          <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
        <% end -%>

        <%- if devise_mapping.omniauthable? %>
          <%- resource_class.omniauth_providers.each do |provider| %>
            <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
          <% end -%>
        <% end -%>
      </div>
    </div>
  </div>
</div>